### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "options" argument must be of type object. Received type object

### ISSUE THREAD

**Issue by youness92** [soyuka/node-rpi-monit#2]
I have tried to run the script on a raspberry pi but unable to make it work properly
Any help would be appreciated, Thanks

at normalizeSpawnArguments (child_process.js:417:11)
at spawn (child_process.js:537:38)
at exec (/home/pi/Documents/node-rpi-monit/node_modules/exec/index.js:35:15)
at Object.fetch (/home/pi/Documents/node-rpi-monit/libs/cpu.js:17:3)
at Object.init (/home/pi/Documents/node-rpi-monit/core/lib.js:14:9)
at /home/pi/Documents/node-rpi-monit/libs/index.js:49:8
at /home/pi/Documents/node-rpi-monit/node_modules/async/lib/async.js:111:13
at Array.forEach (<anonymous>)
at _each (/home/pi/Documents/node-rpi-monit/node_modules/async/lib/async.js:32:24)
at Object.async.each (/home/pi/Documents/node-rpi-monit/node_modules/async/lib/async.js:110:9)

**Comment by soyuka** [comment]
you cut the most important lines...

Anyway I'm not using this project anymore.

**Comment by youness92** [comment]
Bonjour Soyuka,

You did an amazing job to build the js libs for the dashboard, what a pitty to be unable to reuse it.
If you have some time I would appreciate any help to debug that issue.
what lines should I add to the logs ?
